multikino_homepage:
    pattern:  /
    defaults: { _controller: MultikinoBundle:Default:index }
multikino_program:
    pattern:  /program/
    defaults: { _controller: MultikinoBundle:Program:index }
multikino_program_chooseDate:
    pattern:  /program/{branchOfficeId}/
    defaults: { _controller: MultikinoBundle:Program:chooseDate }
multikino_program_showProgram:
    pattern:  /program/{branchOfficeId}/{dateString}/
    defaults: { _controller: MultikinoBundle:Program:showProgram }
multikino_detail:
    pattern:  /detail/{projectionId}
    defaults: { _controller: MultikinoBundle:Detail:index }
multikino_about:
    pattern:  /about/
    defaults: { _controller: MultikinoBundle:About:index }