multikino_homepage:
    pattern:  /
    defaults: { _controller: MultikinoBundle:Default:index }
multikino_program:
    pattern:  /program/
    defaults: { _controller: MultikinoBundle:Program:index }
multikino_detail:
    pattern:  /detail/
    defaults: { _controller: MultikinoBundle:Detail:index }
multikino_about:
    pattern:  /about/
    defaults: { _controller: MultikinoBundle:About:index }