parameters:
    multikino.branch_office_dao.class: PA032\Bundle\MultikinoBundle\DAO\BranchOfficeDAO

services:
    multikino.branch_office_dao:
        class: %multikino.branch_office_dao.class%
        arguments: ["@dao.db_connection"]
